# Neural Gaming Configuration v4.0
# Advanced AI and performance optimization settings

system:
  # System Information
  name: "Neural Gaming Performance System"
  version: "4.0.0"
  build: "2024.01.001"
  
  # Target Hardware Configuration
  target_hardware:
    cpu:
      brand: "Intel i7-9700K"  # or "AMD Ryzen 7 3700X"
      cores: 8
      threads: 8
      base_clock: 3600  # MHz
      boost_clock: 4900  # MHz
      
    gpu:
      brand: "NVIDIA RTX 3080"  # or "AMD RX 6800 XT"
      memory: 10240  # MB
      cuda_cores: 8704
      base_clock: 1440  # MHz
      boost_clock: 1710  # MHz
      
    memory:
      size: 16384  # MB
      type: "DDR4"
      speed: 3200  # MHz
      channels: 2
      
    storage:
      primary:
        type: "NVMe M.2 SSD"
        capacity: 1000  # GB
        read_speed: 7000  # MB/s
        write_speed: 5300  # MB/s
      
    network:
      type: "Ethernet"
      speed: 1000  # Mbps
      latency: 5  # ms (ideal)

ai_engine:
  # AI Engine Configuration
  enabled: true
  learning_enabled: true
  
  # Neural Network Settings
  model:
    input_size: 12
    hidden_layers: [128, 64, 32]
    output_size: 3
    dropout_rate: 0.3
    
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    validation_split: 0.2
    
  # Performance Prediction
  prediction:
    horizon_seconds: 60
    confidence_threshold: 0.7
    update_interval: 5.0
    
  # Anomaly Detection
  anomaly:
    contamination: 0.1
    sensitivity: 0.8
    alert_threshold: -0.5
    
  # Caching
  cache:
    max_size: 2000
    ttl_seconds: 120
    cleanup_interval: 300

performance_optimizer:
  # Performance Optimizer Configuration
  enabled: true
  
  # Threading
  max_workers: 8
  use_process_pool: true
  
  # Monitoring
  monitoring:
    interval: 1.0  # seconds
    history_size: 1000
    metrics_retention: 3600  # seconds
    
  # Optimization Thresholds
  thresholds:
    cpu_usage_high: 85.0
    memory_usage_high: 90.0
    temperature_high: 80.0
    fps_low: 60.0
    latency_high: 50.0
    
  # Auto-optimization
  auto_optimize:
    enabled: true
    cooldown: 30.0  # seconds
    max_frequency: 10  # per hour
    
  # Memory Management
  memory:
    pool_sizes:
      small: [256, 50]    # [size_bytes, count]
      medium: [4096, 20]
      large: [65536, 5]
    gc_threshold: 0.85
    
windows_optimizer:
  # Windows-specific Optimizations
  enabled: true
  require_admin: true
  
  # CPU Optimizations
  cpu:
    high_performance_plan: true
    disable_parking: true
    turbo_boost: true
    minimum_state: 100
    interrupt_priority: true
    
  # Memory Optimizations
  memory:
    disable_compression: true
    large_system_cache: true
    disable_prefetch: true
    optimize_heap: true
    disable_integrity: false  # Security consideration
    
  # GPU Optimizations
  gpu:
    hardware_scheduling: true
    disable_fullscreen_opt: true
    game_mode: true
    variable_refresh_rate: true
    
  # Network Optimizations
  network:
    tcp_stack: true
    disable_nagle: true
    rss_enabled: true
    disable_throttling: true
    fast_dns: true
    
  # Storage Optimizations
  storage:
    disable_indexing: true
    enable_trim: true
    disable_defrag: true
    write_caching: true
    directstorage: true
    
  # Gaming Optimizations
  gaming:
    game_mode: true
    disable_dvr: true
    focus_assist: true
    optimize_visuals: true
    ultimate_power: true

web_dashboard:
  # Web Dashboard Configuration
  enabled: true
  
  # Server Settings
  server:
    host: "0.0.0.0"
    port: 5000
    debug: false
    use_ssl: false
    
  # WebSocket Settings
  socketio:
    cors_origins: "*"
    ping_timeout: 60
    ping_interval: 25
    
  # UI Settings
  ui:
    theme: "neural_2040"
    auto_refresh: 2.0  # seconds
    animation_speed: "normal"
    particle_count: 100
    
  # Performance Monitoring
  monitoring:
    update_interval: 1.0  # seconds
    history_points: 300  # 5 minutes at 1s intervals
    real_time_charts: true
    
  # 3D Visualization
  visualization_3d:
    enabled: true
    fps_target: 60
    anti_aliasing: true
    particles: true
    
discord_bot:
  # Discord Bot Configuration
  enabled: false  # Requires token
  
  # Bot Settings
  bot:
    command_prefix: "!fps "
    case_sensitive: false
    description: "SUHA FPS+ v4.0 Neural Gaming Assistant"
    activity: "gaming performance"
    
  # Features
  features:
    ai_recommendations: true
    performance_graphs: true
    session_tracking: true
    alerts: true
    leaderboards: true
    
  # Monitoring
  monitoring:
    performance_interval: 30.0  # seconds
    ai_analysis_interval: 300.0  # 5 minutes
    data_backup_interval: 3600.0  # 1 hour
    
  # Alerts
  alerts:
    fps_threshold: 60
    latency_threshold: 50
    temperature_threshold: 80
    cpu_threshold: 90

# Gaming Profiles
gaming_profiles:
  competitive:
    name: "Competitive Gaming"
    description: "Maximum performance for competitive play"
    settings:
      cpu_priority: "high"
      memory_optimization: "aggressive"
      network_optimization: "low_latency"
      visual_effects: "minimal"
      background_apps: "disable"
      
  streaming:
    name: "Streaming Gaming"
    description: "Balanced performance for gaming + streaming"
    settings:
      cpu_priority: "above_normal"
      memory_optimization: "balanced"
      network_optimization: "bandwidth_aware"
      visual_effects: "moderate" 
      background_apps: "selective"
      
  casual:
    name: "Casual Gaming"
    description: "Optimized for casual gaming experience"
    settings:
      cpu_priority: "normal"
      memory_optimization: "standard"
      network_optimization: "standard"
      visual_effects: "enhanced"
      background_apps: "allow"
      
  vr:
    name: "VR Gaming"
    description: "Specialized optimization for VR gaming"
    settings:
      cpu_priority: "high"
      memory_optimization: "aggressive"
      network_optimization: "low_latency"
      visual_effects: "vr_optimized"
      background_apps: "disable"
      usb_optimization: true
      motion_smoothing: true

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  handlers:
    console:
      enabled: true
      level: "INFO"
      colored: true
      
    file:
      enabled: true
      level: "DEBUG"
      path: "logs/"
      filename: "suha_fps_v4.log"
      max_size: 10485760  # 10MB
      backup_count: 5
      
    performance:
      enabled: true
      path: "logs/performance/"
      retention_days: 7

# Security Settings
security:
  # API Security
  api:
    require_auth: false
    rate_limiting: true
    max_requests_per_minute: 60
    
  # Data Protection
  data:
    encrypt_sensitive: true
    secure_storage: true
    data_retention_days: 30
    
  # Network Security
  network:
    allowed_hosts: ["localhost", "127.0.0.1"]
    disable_cors: false

# Advanced Settings
advanced:
  # Experimental Features
  experimental:
    gpu_compute_ai: true
    predictive_optimization: true
    neural_network_caching: true
    quantum_optimization: false  # Future feature
    
  # Debug Options
  debug:
    enable_profiling: false
    memory_tracking: false
    performance_counters: true
    ai_model_debugging: false
    
  # Compatibility
  compatibility:
    legacy_support: false
    fallback_modes: true
    safe_mode_available: true