# Gaming Performance Monitor Configuration
# Optimized for Intel i7-9700K + RTX 3080 + 16GB RAM + M.2 SSD setup

# System Monitoring Settings
monitoring:
  update_interval: 1.0  # seconds
  data_retention_days: 30
  enable_logging: true
  log_level: INFO

# Performance Thresholds
thresholds:
  # FPS monitoring
  min_fps: 60
  target_fps: 120
  fps_drop_threshold: 10  # significant drop in FPS
  frame_time_target: 8.33  # ms (120 FPS)
  
  # System temperatures (Celsius)
  max_cpu_temp: 85
  max_gpu_temp: 83
  warning_cpu_temp: 80
  warning_gpu_temp: 78
  
  # Memory usage (percentage)
  max_memory_usage: 90
  warning_memory_usage: 85
  max_vram_usage: 90
  
  # Network performance
  max_ping: 50  # ms
  max_jitter: 10  # ms
  max_packet_loss: 1.0  # percentage
  min_bandwidth_down: 100  # Mbps
  min_bandwidth_up: 20  # Mbps

# Hardware-Specific Optimizations
hardware:
  cpu:
    model: "Intel i7-9700K"
    base_clock: 3600  # MHz
    boost_clock: 4900  # MHz
    cores: 8
    threads: 8
    enable_turbo_boost: true
    enable_hyperthreading: false  # Not available on 9700K
    power_profile: "high_performance"
    
  gpu:
    model: "NVIDIA RTX 3080"
    base_clock: 1440  # MHz
    boost_clock: 1710  # MHz
    memory_clock: 9500  # MHz
    power_limit: 100  # percentage
    enable_gpu_boost: true
    fan_curve_aggressive: true
    
  memory:
    capacity: 16  # GB
    speed: 3200  # MHz
    enable_xmp: true
    timings: "auto"
    
  storage:
    type: "M.2_NVMe"
    capacity: 1000  # GB
    max_speed: 7000  # MB/s
    enable_write_cache: true
    disable_indexing: true

# Windows Optimizations
windows:
  game_mode: true
  disable_defender_realtime: true  # During gaming only
  disable_background_apps: true
  optimize_visual_effects: true
  disable_notifications: true
  priority_boost: true
  disable_fullscreen_optimization: false
  
  # Services to disable during gaming
  disable_services:
    - "Windows Update"
    - "Windows Search"
    - "SuperFetch"
    - "Print Spooler"
    - "Fax Service"
    - "Windows Error Reporting"
    - "Diagnostic Policy Service"
  
  # Power settings
  power_plan: "high_performance"
  disable_usb_suspend: true
  disable_pcie_power_management: true

# Network Optimizations
network:
  dns_servers:
    primary: "1.1.1.1"    # Cloudflare
    secondary: "8.8.8.8"  # Google
  
  tcp_optimizations:
    disable_nagle: true
    tcp_window_scaling: true
    receive_window_size: 65536
    chimney_offload: true
    rss_enabled: true
    
  qos:
    gaming_priority: "high"
    background_limit: 10  # percentage of bandwidth
    
# Game Detection
games:
  detection_methods:
    - "process_name"
    - "window_title"
    - "fullscreen_detection"
    
  common_games:
    - "League of Legends"
    - "Counter-Strike 2"
    - "Valorant"
    - "Fortnite"
    - "Call of Duty"
    - "Apex Legends"
    - "Overwatch 2"
    - "Cyberpunk 2077"
    - "Elden Ring"

# Dashboard Settings
dashboard:
  theme: "dark"
  update_rate: 500  # milliseconds
  show_graphs: true
  graph_history: 300  # seconds
  auto_hide: false
  always_on_top: true
  transparency: 0.9

# Notifications
notifications:
  enable_desktop: true
  enable_sound: false
  enable_email: false
  
  severity_levels:
    critical: ["high_temp", "system_crash"]
    warning: ["fps_drop", "high_memory", "high_ping"]
    info: ["optimization_applied", "system_stable"]

# Database Settings
database:
  type: "sqlite"
  path: "performance_data.db"
  backup_enabled: true
  backup_interval: 24  # hours
  
# Logging
logging:
  file_path: "logs/performance_monitor.log"
  max_file_size: 10  # MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Safety and Recovery
safety:
  create_restore_point: true
  backup_registry: true
  enable_rollback: true
  max_rollback_time: 3600  # seconds
  
# Advanced Settings
advanced:
  enable_overclocking: false  # Requires manual confirmation
  enable_undervolting: false
  custom_fan_curves: true
  memory_compression: true
  prefetch_optimization: true